---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: elasticsearch
  chart:
    repository: https://helm.elastic.co/
    name: elasticsearch
    version: 7.4.0
  values:
    image: docker.elastic.co/elasticsearch/elasticsearch
    imageTag: 7.4.0
    replicas: 2
    antiAffinity: none
    persistence:
      enabled: false
