---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~7.4
spec:
  releaseName: elasticsearch
  chart:
    repository: https://helm.elastic.co/
    name: helm/elasticsearch/elasticsearch
    version: 7.4.0
  values:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    imageTag: 7.4.0
    persistence:
      enabled: false
