---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: logging
spec:
  releaseName: filebeat
  chart:
    repository: https://helm.elastic.co/
    name: filebeat
    version: 7.4.0
  values:
    image: docker.elastic.co/beats/filebeat
    imageTag: 7.4.0
    filebeatConfig:
      filebeat.yml: |
        filebeat.modules:
        - module: elasticsearch

        filebeat.inputs:
        - type: docker
          containers.ids:
          - '*'
          processors:
          - add_kubernetes_metadata:
              in_cluster: true

        output.elasticsearch:
          hosts: ['elasticsearch-master:9200']
