---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: logging
spec:
  releaseName: filebeat
  chart:
    repository: https://helm.elastic.co/
    name: filebeat
    version: 7.4.0
  values:
    image: docker.elastic.co/beats/filebeat
    imageTag: 7.4.0
    filebeatConfig:
      filebeat.yml: |
        output.elasticsearch:
          hosts: ["elasticsearch-master:9200"]
        setup.kibana:
          host: "http://kibana-kibana:5601"
